pipeline {
    agent any
    stages {
        stage('Build Application') {
            steps {
                sh 'mvn -f java-tomcat-sample/pom.xml clean package'
            }
            post {
                success {
                    echo "Now archiving the Artifacts.."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }
        stage('Deploy in staging env'){
            steps {
                build job: 'DeployApplicationStagingEnv'
                }
          }
       }
    }
